config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  
  resources :party,  only: [:show, :new, :create, :edit, :update, :destroy]
  put 'party/:id/conclude_flip' => 'party#conclude_flip', as: :party_conclude_flip
  put 'party/:id/results_released_flip' => 'party#results_released_flip', as: :results_released_flip
  get 'party/:id/view_results' => 'party#view_results', as: :party_view_results
  get 'party/state_check/:id' => 'party#state_check', as: :party_state_check
  get 'party/:id/get_status' => 'party#get_status', as: :party_get_status

  resources :party_invitation, only: [:create]
  put 'party_invitation/:id/accept' => 'party_invitation#accept', as: :party_invitation_accept

  put 'entry_upsert_clearname/:entry_id' => 'entry#upsert_clearname', as: :entry_user_upsert_clearname

  resources :vote, only: [:update]
  get 'vote/:id/dashboard_ajax' => 'vote#dashboard_ajax', as: :vote_dashboard_ajax

  get 'wine/ajax_search'
  
  put 'shout/create'
  get 'shout/:id/dashboard_ajax' => 'shout#dashboard_ajax', as: :shout_dashboard_ajax
  
  get 'user/:id/edit' => 'user#edit', as: :user_edit
  put 'user/:id' => 'user#update', as: :user_update
  put 'user/update/:user_id' => 'user#update_nickname', as: :update_user_nickname
  delete 'user/:id' => 'user#destroy', as: :user_destroy

  root :to => "static#index"

  get '/signout' => 'sessions#destroy'

end

app/models/party.rb
# == Schema Information
#
# Table name: parties
#
#  id                :integer          not null, primary key
#  name              :string
#  event_date        :datetime
#  event_key         :string
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  user_id           :integer
#  concluded         :boolean
#  results_released  :boolean
#  disguise_theme_id :integer
#

class Party < ActiveRecord::Base
	validates :name, :user_id, presence: true
	validates :event_key, presence: true, uniqueness: { case_sensitive: false }
	validate :valid_datetime?
	validates :name, presence: true
	validates :disguise_theme_id, presence: true

	after_initialize :set_new_record_values
	after_create :create_owners_membership
	after_update :check_disguise_theme_update

	# Associations
	belongs_to :user
	has_many :party_invitations, dependent: :destroy
	has_many :party_memberships, dependent: :destroy
	has_many :entries, dependent: :destroy
	has_many :votes, dependent: :destroy
	has_many :shouts, dependent: :destroy

	def valid_datetime?
		begin
			DateTime.parse(self.event_date.to_s)
		rescue => error
			errors.add(:event_date, "is missing or invalid")
		end
	end

	def event_key_generator()
		valid_chars = "ABCDEFGHJKLMNPQRSTUVWXYZ123456789" #omitting ambiguous chars
		new_key = ""
		7.times do
			new_key << valid_chars[rand(valid_chars.length)]
		end
		return new_key
	end
	
	def getMembersAvgScores
		memberScoresArr = []
		partyAttendee_ids = party_memberships.pluck(:user_id)
		User.find(partyAttendee_ids).each do |attendeeUser|
			
			scores = attendeeUser.votes(party_id: self.id).pluck(:score)
			
			nonNil_scores = scores.compact
			average = nonNil_scores.sum / nonNil_scores.size.to_f
			if average.nan?
				next
			end
			
			newHash = {"email"=> attendeeUser.email, "average_score" => average }
			
			memberScoresArr.push(newHash)
		end
		
		# Sort in descending score order
		memberScoresArr.sort_by! { |item| -1*item["average_score"] }
		
		return memberScoresArr
	end
	
	def flip_concluded
		# Contains logic for flipping party state
		
		# Allow concluded: false-->true only if there exist entries & votes
		if !self.concluded && self.entries.size>0 && self.votes.size>0
			self.concluded = true
			self.results_released = false
			self.save
			return "Party is now concluded"
		elsif !self.concluded
			# Party is !concluded, and will stay !concluded because entries and votes are needed
			return "Party is still in progress.  Cannot close party if no one has voted"
		else
			# Party is concluded, toggle back to !concluded
			self.concluded = false
			self.results_released = false
			self.save
			return "Party is now in progress"
		end
	end

	private

		def set_new_record_values
			if self.new_record? #Only for new record
				begin
					self.event_key = event_key_generator()
				end while (not Party.find_by_event_key(self.event_key).blank?)

				self.concluded = false
				self.results_released = false
			end
			true
		end

		def create_owners_membership
			# The party owner must be a member to their own party
			PartyMembership.create(party_id: self.id, user_id: self.user_id)
		end
		
		def check_disguise_theme_update
			# IF the disguise_theme has been updated, all Party's entries need to get new Disguises
			if self.disguise_theme_id_changed?
				self.entries.each do |partyEntry|
					partyEntry.find_new_disguise_id
				end
			end
		end
		
end

app/controllers/party_controller.rb
class PartyController < ApplicationController
	#Access limitations etc.
	before_action :authenticate_user!
	before_action :correct_user_party_show, only: [:show, :state_check, :get_status]
	before_action :correct_user_party_host, only: [:destroy, :update, :conclude]
	before_action :check_if_party_concluded, only: :view_results

	def new
		@party = Party.new
	end

	def create
		@party = current_user.parties.new(party_params)
		if @party.save
			flash[:success] = "Party created!"
			redirect_to :action => 'show', :id => @party.id
		else
			render "new"
		end
	end

	def edit
		@party = current_user.parties.find_by_id(params[:id])
		if !@party
			flash[:error] = "Something went wrong"
			redirect_to root_path
		end
	end

	def update
		@party = current_user.parties.find_by_id(params[:id])
		if !@party.nil? && @party.update_attributes(party_params)
			flash[:success] = "Party updated!"
			redirect_to :action => 'show', :id => @party.id
		else
			flash[:error] = "Something went wrong"
			redirect_to root_path
		end
	end

	def destroy
		@party = current_user.parties.find_by_id(params[:id])
		@party.destroy
		if @party.destroyed?
			flash[:notice] = "Party deleted"
		else
			flash[:error] = "Something went wrong"
		end
		redirect_to root_path
	end
	
	def show
		@party = Party.find(params[:id])
		@invitation = PartyInvitation.new(party_id: params[:id])
		@entry = current_user.find_or_build_entry(params[:id])

		# all_entries used by Host to give codenames
		if current_user.id==@party.user_id
			@invitations = PartyInvitation.where(party_id: params[:id])
			@acceptees = User.where(id: @party.party_memberships.pluck(:user_id))
			
			all_entries_unordered = Entry.where(party_id: params[:id])
			@all_entries = all_entries_unordered.sort { |a,b| a.codename <=> b.codename }
			@users_still_need_entries = Entry.party_members_accepted_invite_no_entry(params[:id])
		else
			@all_entries = nil
			@users_still_need_entries = nil
		end
		
		# For the host
		if @party.concluded
			# Results only matter when party is in concluded state
			@results = Vote.present_results(params[:id], current_user.id)	
		end

		@votes = Vote.retrieve_votes(params[:id],current_user.id)
		@shout = current_user.shouts.new(party_id: params[:id])
	end

	def conclude_flip
		@party = current_user.parties.find_by_id(params[:id])
		
		if !@party.nil?
			# Whenever the concluded flag is flipped, set results_released to false
			msg = @party.flip_concluded
			flash[:notice] = msg
			redirect_to :action => 'show', :id => @party.id
		else
			flash[:error] = "Something went wrong"
			redirect_to root_path
		end
	end
	
	def results_released_flip
		@party = current_user.parties.find_by_id(params[:id])
		
		if !@party.nil?
			@party.update(results_released: !@party.results_released)
			if @party.results_released
				flash[:notice] = "Party Results Released to All"
			else
				flash[:notice] = "Party Results Withdrawn"
			end
			redirect_to :action => 'show', :id => @party.id
		else
			flash[:error] = "Something went wrong"
			redirect_to root_path
		end
	end

	def view_results
		@party = Party.find(params[:id])
		@results = Vote.present_results(params[:id], current_user.id)
		@user_averages = @party.getMembersAvgScores
		@voting_breakdowns = Vote.voting_breakdown(params[:id], current_user.id)
	end
	
	def state_check
		@party = Party.find(params[:id])
		respond_to do |format|
			format.json {
				render :json => {
					:concluded => @party.concluded,
					:results_released => @party.results_released,
					:number_of_entries => @party.entries.where.not(disguise_id: nil).size
				}.to_json, :status => :ok
			}
		end
	end
	
	def get_status
		@party = Party.find(params[:id])
		@stats = Vote.spectate_votes(@party.id)
		respond_to do |format|
			format.json {
				render :json => { :current_number_votes => @stats["current_number_votes"], 
					:max_number_votes => @stats["max_number_votes"],
					:vote_completion => @stats["vote_completion"]}.to_json, :status => :ok
			}
		end
	end

  private 

  	def party_params
		params[:party].permit(:name,:event_date, :disguise_theme_id)
	end

	def check_if_party_concluded
		if !Party.find(params[:id]).concluded
			redirect_to party_path(params[:id])
		end
	end

	def correct_user_party_show
		party_members = PartyMembership.where(party_id: params[:id]).pluck(:user_id)
		if !party_members.include?(current_user.id)
			#User is not a member of the Party
			flash[:error] = "Something went wrong"
  			redirect_to root_path
		end
	end

end

app/helpers/party_helper.rb
module PartyHelper
end

app/views/party/_acceptees.html.erb
<% if acceptees.size==0 %>
	<li>(none)</li>
<% else %>
	<% acceptees.each do |user| %>
		<li><%= user.email + (user.needs_name ? "" : "  :  (#{user.name})") %></li>
	<% end %>
<% end %>

app/views/party/_invitelist.html.erb
<% if invitations.size==0 %>
	<li>(none)</li>
<% else %>
	<% invitations.each do |invite| %>
		<li id="invite_email_<%= invite.id %>"><%= invite.email %></li>
	<% end %>
<% end %>

app/views/party/_results_final_averages.html.erb
<ul class="collection">
    <li class="collection-item">
        <p class="presentation_item_title">Final Averages - All Wines - <a onclick="toggleContentByID('results-block-chart')">show/hide</a></p>
        <div id="results-block-chart" >
            <div class="medlarge_display">
                <div id="uvhart_results_ordered"></div>
            </div>
            <p class="presentation_item_title">Full Rank List</p>
            <table class="striped">
                <thead>
                    <tr>
                        <th>Score</th>
                        <th>Wine</th>
                    </tr>
                </thead>
                <tbody>
                    <% @results["final_averages"]["averages"].reverse.each_with_index do |avg,indx| %>
                        <tr>
                            <td>
                                <ul class="results_ordinal_column">
                                    <li><b><%= ActiveSupport::Inflector.ordinalize(indx+1) %></b></li>
                                    <li><b><%= avg %></b></li>
                                </ul>
                            </td>
                            <td>
                                <ul>
                                    <li>"<%= @results["final_averages"]["codenames"].reverse[indx] %>"</li>
                                    <li><%= @results["final_averages"]["clearnames"].reverse[indx] %></li>
                                    <li><%= @results["final_averages"]["name"].reverse[indx] %></li>
                                    <% if current_user.id!=@party.user_id %>
                                        <li><b>Your Vote:</b> <%= @results["final_averages"]["own_vote"].reverse[indx] %></li>
                                        <li><b>Your Note:</b> <%= @results["final_averages"]["own_note"].reverse[indx] %></li>
                                    <% end %>
                                </ul>
                            </td>
                        </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
    </li>



</ul>


<script type="text/javascript" charset="utf-8">

var graphdef = {
    categories : ['Results'],
    dataset : {
        'Results' : [
        	<% @results["final_averages"]["averages"].reverse.each_with_index do |avg,indx| %>
        		{ name : '<%= @results["final_averages"]["codenames"].reverse[indx] %>', value : <%= avg %> },
        	<% end %>
        ]
    }
};
var graphConfig = {
    meta : {
        position : '#uvhart_results_ordered',
        hlabel : 'Score'
    },
    effects : {
        duration : 500,
        showhovertext : false
    },
    dimension : {
        width : 250,
        height : <%= 40*@results["final_averages"]["averages"].size %>
    },
    graph : {
        orientation : 'Horizontal'
    },
    legend : {
        showlegends : false
    },
    margin : {
        top : 15,
        bottom : 75,
        left : 120,
        right : 15
    },
    axis : {
        fontsize : 18,
        ticks : 5
    },
    scale : {
        ordinality : 0.2
    },
    label : {
        fontsize : 14
    }
};
var chart = uv.chart('Bar',graphdef,graphConfig);

</script>

app/views/party/_results_voting_breakdown.html.erb
<ul class="collection">
    <li class="collection-item">
    	<p class="presentation_item_title">Scoring Profile by Wine - <a onclick="toggleContentByID('results-block-voting-breakdown')">show/hide</a></p>
		<div id="results-block-voting-breakdown" >
			<p style="margin-bottom:30px;">First to worst, with your vote highlighted</p>
		
			
			<% @voting_breakdowns.each_with_index do |voting_breakdown, indx| %>
				<%= render partial: "voting_breakdown2", object: voting_breakdown, locals: {indxx: indx} %>
			<% end %>
		</div>
	</li>
</ul>

app/views/party/edit.html.erb
<h2>Modify the Party</h2>

<%= form_for @party do |f| %>
  <%= f.label :name %>:
  <%= f.text_field :name %><br />

  <%= f.label :event_date %>:
  <%= f.text_field :event_date %><br />

  <%= f.submit "Update" %>
<% end %>

app/views/party/new.html.erb
<div class="row">
    <div class="col offset-l3 l6 offset-m2 m8 s12">
		<h2>Start your party here</h2>

		<%= form_for @party, url: party_index_path do |f| %>
		  <%= f.label :name %>:
		  <%= f.text_field :name %><br />

		  <%= f.label :event_date %>:
		  <%= f.text_field :event_date %><br />
		  
		  <%= f.label "Disguise theme (don't worry, you can change this later):" %>:
		  <%= f.select :disguise_theme_id, options_for_select(DisguiseTheme.all.collect{|disguiseTheme| [disguiseTheme.name, disguiseTheme.id]}, :selected => DisguiseTheme.first.id), {}, { :class => "browser-default" } %>

		  <%= f.submit "Create Party", :class => "btn" %>
		<% end %>
  </div>
</div>

app/views/party/show.html.erb
<div class="party_show_for_containers">

<div class="row">
	<div class="col s12 m12 l12">
		<h3><%= @party.name %></h3>
		<h5><%= @party.event_date.strftime("%b %d, %Y") %></h5>
		<% if current_user.id==@party.user_id && (@party.event_date < Time.now + 36.hours) %>
			<div id="party_concluded_switch" class="switch">
				<label>
					<span class="<%= @party.concluded ? 'switch_option_selected' : '' %>">Everyone's Done</span>
					<input type="checkbox">
					<span id="" class="lever" onclick="$('#party_conclude_flip_btn').click();"></span>
					<span class="<%= @party.concluded ? '' : 'switch_option_selected' %>">Tasting In Progress</span>
				</label>
			</div>
			<div style="display:none;">
				<%= form_for @party, method: :put, url: party_conclude_flip_path do |f| %>
					<%= f.hidden_field :concluded %>
					<%= f.button "conclude-flip, this button is always hidden", :id => "party_conclude_flip_btn" %>
				<% end %>
			</div>
			<p><%= link_to "Social Dashboard", "#", :onclick => "checkIfMobileWidthBeforeExec('To view the dashboard, log-on using a device with a larger display',openDashboardModal);" %></p>
			<% if !@party.concluded %>
				<p><a id="party_progress_link" href="#" onclick="getPartyStatus();">Check Everyone's Progress</a><span id="party_progress_text"></span></p>
				<!-- Modal Structure -->
				<div id="modal1" class="modal">
					<div class="modal-content">
						<span><a href="#!" class=" modal-action modal-close">(close)</a></span>
						<h5>How to have a successful party</h5>
						<p>Before the party</p>
						<ol>
							<li>Invite people by email address</li>
							<li>Your guests should accept the invite, and add their wine to the party</li>
						</ol>
						<p>Party time</p>
						<ol>
							<li>As people arrive, take their wine bottle to another room, disguise it (with brown bag or other), and label it with the disguise name we automatically assigned (found at the bottom of this page)</li>
							<li>Bring all your disguised bottles to the party room, tell people to refresh the web page and start voting</li>
							<li>Click the 'Social Dashboard' link to see what people are saying, and display it on a big screen if you have it</li>
							<li>Shout out a 5 min warning, and when it's time switch to "Everyones Done"</li>
							<li>Click 'Present Results' and show everyone</li>
							<li>Click 'Release Results' so everyone can view for themselves</li>
						</ol>
					</div>
					<div class="modal-footer">
						<a href="#!" class=" modal-action modal-close waves-effect waves-green btn">Got it!</a>
					</div>
				</div>
			<% end %>
			
			<% if !@party.concluded %>
				<p><a class="modal-trigger" href="#modal1">Need some help?</a></p>
			<% end %>
			<% if @party.concluded %>
				<div id="party_results_released_switch" class="switch">
					<label>
						<span class="<%= @party.results_released ? '' : 'switch_option_selected' %>">Results Hidden</span>
						<input type="checkbox">
						<span class="lever" onclick="$('#party_release_results_btn').click();"></span>
						<span class="<%= @party.results_released ? 'switch_option_selected' : '' %>">Results Released to Everyone</span>
					</label>
				</div>
				<div style="display:none;">
					<%= form_for @party, method: :put, url: results_released_flip_path do |f| %>
						<%= f.hidden_field :results_released %>
						<%= f.button "this button is always hidden", :id => "party_release_results_btn" %>
					<% end %>
				</div>
				
				<p><a href="#" onclick="checkIfMobileWidthBeforeExec('To access the results presentation mode, log-on using a device with a larger display',openResultsModal);">Present Results (this is fun!)</a></p>
				<%= render "results_presentation_modal" %>
				
				<p><%= link_to "View Results", party_view_results_path(@party.id) %></p>
			<% end %>
		<% elsif current_user.id==@party.user_id && (@party.event_date > Time.now + 36.hours) %>
			<p>The party is more than a day away.</p>
			<p>Your admin controls will appear here the day of the party.</p>
		<% elsif current_user.id!=@party.user_id && @party.results_released %>
			<h5><%= link_to "See Results!", party_view_results_path(@party.id) %></h5>
		<% end %>
	</div>
</div>

<script>
	<% if @party.concluded %>
		$('div#party_concluded_switch input').prop('checked', false);
	<% else %>
		$('div#party_concluded_switch input').prop('checked', true);
	<% end %>
	
	<% if @party.results_released %>
		$('div#party_results_released_switch input').prop('checked', true);
	<% else %>
		$('div#party_results_released_switch input').prop('checked', false);
	<% end %>
	
	<% if current_user.id==@party.user_id %>
		function getPartyStatus() {
			$("#party_progress_link").addClass('link-not-active');
			$.ajax({
				type: "GET",
				callback: "JSON",
				dataType: "json",
				url: '/party/' + <%= @party.id %> + '/get_status.json',
				success: function(msg) {
					// Present the status
					$("span#party_progress_text").hide();
					$("span#party_progress_text").text(msg.vote_completion + ' - ' + msg.current_number_votes + ' of ' + msg.max_number_votes + ' tastings complete');
					$("span#party_progress_text").fadeIn();
					setTimeout(function() { 
						$("span#party_progress_text").fadeOut(); 
						$("#party_progress_link").removeClass('link-not-active');
					}, 5000);
				},
				error: function(msg) {
					$("#party_progress_link").removeClass('link-not-active');
					alert( "Hmm, something went wrong." );
				}
			});
		}
	<% end %>
</script>

<% if current_user.id==@party.user_id %>
	<%= render partial: "social_dashboard" %>
<% end %>

<div class="row">
	<% if current_user.id==@party.user_id && !@party.concluded %>
		<div class="col s12 m12 l9">
			<h4>Send Invitations</h4>
			<table>
				<tbody>
					<tr>
						<%= form_for @invitation, url: party_invitation_index_path(@invitation), html: { method: :post }, remote: true do |f| %>
							<td id="invite_email_table_textfield">
								<%= f.text_field :email, :placeholder => "who@where.com" %>
								<%= f.hidden_field :party_id %>
							</td>
							<td id="invite_email_table_button">
								<%= f.button "Send", :class => "btn" %>
							</td>							
						<% end %>
					</tr>
				</tbody>
			</table>
			<div id="flash_partyinvite"></div>
			<ul class="collapsible" data-collapsible="accordion">
			    <li>
					<div id="pending_invites_header" class="collapsible-header">Pending Invitations (<%= @invitations.size %>)</div>
					<div class="collapsible-body">
						<div id="pending_invites">
							<ul><%= render partial: "invitelist", locals: {invitations: @invitations} %></ul>
						</div>
					</div>
			    </li>
			    <li>
					<div id="accpeted_invites_header" class="collapsible-header">Accepted (<%= @acceptees.size %>)</div>
					<div class="collapsible-body">
						<div id="accepted_invitees">
							<ul><%= render partial: "acceptees", locals: {acceptees: @acceptees} %></ul>
						</div>
					</div>
			    </li>
			</ul>
				
		</div>
	<% end %>
</div>
<% if !@party.concluded %>
	<div class="row">
		<div class="col s12 m12 l9">
			
		</div>
	</div>
	<div id="div_clearname_form" class="row">
		<div class="col s12 m12 l8">
			<h4>What wine did you bring?</h4>
			<% if current_user.id==@party.user_id %>
				<span>As the host, you can't vote.  But you can still submit a wine.</span>
			<% end %>
			<% if @entry.id.nil? %>
				<div id="register_reminder">
					<span style="font-weight:bold;">(You still need to add your wine bottle)</span>
				</div>
			<% end %>
			<input id="clearname_textfield2" type="text" class="browser-default" value="<%= @entry.clearname.nil? ? "" : @entry.clearname %>" placeholder="include name and year, ex. Cote du Rhone 2011" ></input>
			<div>
				<button id="clearname_submit_btn" name="button" type="button" class="btn btn-default disabled" onclick="submitEntryUpsert(<%= @entry.id.nil? ? "null" : @entry.id %>, <%= current_user.id %>, <%= @party.id %>)">Save</button>
				<button id="clearname_cancel_btn" name="button" type="button" class="btn btn-default disabled" onclick="reverUserEntryValue()">Cancel</button>
			</div>
		</div>
	</div>
	
	<script>
		previousClearname = "<%= @entry.clearname.nil? ? "" : @entry.clearname %>";
		$("#clearname_textfield2").keyup(function () { onEntryChange() });

		$(document).on('page:load ready', autoUpdateWineQuery());
	</script>
<% end %>

</div>
<div class="party_show_for_containers">
	<div class="row">
		<div id="shout_out_div" class="col s12 m12 l9">
			<h4>Give the Party a Shout!</h4>
			<%= form_for @shout, url: shout_create_path do |f| %>
				<%= f.hidden_field :user_id, id: "shout_user_id" %>
				<%= f.hidden_field :party_id, id: "shout_party_id" %>
				<%= f.text_area :content, :id => "shout_text_area", :class => "materialize-textarea", :placeholder => "say hi to the party!", :class => "browser-default"  %>
				<button id="shout_text_area_save" onclick="submitShoutOut()" type="button" class="btn btn-default disabled">Send!</button>
				<button id="shout_text_area_cancel" onclick="clearShoutOUt()" type="button" class="btn btn-default disabled">Cancel</button>
			<% end %>
		</div>
	</div>
</div>

<div class="party_show_for_containers">

<script>
	$("#shout_text_area").keyup(function () { onShoutChange() });
</script>


<div class="row">
	<% if current_user.id!=@party.user_id %>
		<div class="col s12 m12 l12">
			<h4>Rate (not rank) other wines here...</h4>
			<% if !@party.concluded %>
				<p>(alphabetical order)</p>
				<%= render partial: "vote_list_ajax", locals: {votes: @votes} %>
				<% if @votes.size==0 %>
					<p><i>No one has submitted an entry yet, hold tight!</i></p>
				<% end %>
			<% else %>
				<p><i>Voting has been closed by the host ...</i></p>
			<% end %>
			<% if @party.results_released %>
				<h5><%= link_to "See Results!", party_view_results_path(@party.id) %></h5>
			<% else %>
				<p><i>Results haven't been released, ... yet.</i></p>
			<% end %>
		</div>
	<% end %>

	<% if current_user.id==@party.user_id %>
		
		<div class="col s12 m12 l12">
			<h4>Wine Code Names</h4>
			<% if !@party.concluded %>
				<%= form_for @party, url: "/party/#{@party.id}" do |f| %>
					<div style="width:220px; float:left;">
					<%= f.select :disguise_theme_id, options_for_select(DisguiseTheme.all.collect{|disguiseTheme| [disguiseTheme.name, disguiseTheme.id]}, :selected => @party.disguise_theme_id), {}, { :class => "browser-default" } %>
					</div>
					<div style="float:left; margin-left:15px;">
					<%= f.submit "Change Theme", :class => "btn", data: { confirm: 'Are you sure you want to change the theme?  (The previous theme assignments will be lost.)' } %>
					</div>
					<div style="clear:both;">&nbsp;</div>
				<% end %>
			<% end %>
			<% if !@users_still_need_entries.nil? %>
				<h6>These people still need to add their wine to the party!</h6>
				<% @users_still_need_entries.each do |email| %>
					<p>&#8680; <%= email %></p>
				<% end %>
			<% end %>
			<%= render partial: "all_entries", locals: {all_entries: @all_entries} %>
		</div>
	<% end %>
</div>

<div class="row">
	<% if current_user.id==@party.user_id %>
		<div class="col s12 m12 l12">
			<h4>Delete <%= @party.name %></h4>
			<h5>(this is permanent)</h5>
			<%= link_to 'Delete',url_for(action: :destroy,id: @party.id),data: {confirm: "Are you sure?",method: :delete}, :class => "btn", :id => "delete-party-link" %>
		</div>
	<% end %>
</div>

</div>

<div id="footer-buffer"></div>

<div id="footer" class="page-footer">
	<div class="container">
		<div class="row">
			<div class="col s6">
						<div class="footer-left-div">
							<h6>New party content!</h6>
						</div>
			</div>
			<div class="col s6">
				<div class="footer-right-div">
					<button class="btn btn-default" onclick="window.location.reload();">Refresh!</button>
				</div>
			</div>
		</div>
	</div>
</div>

<script>
	$(document).on('page:load ready', function() {
	    if ($('div.party_show_for_containers').width() > 992) {
	        $('div.party_show_for_containers').addClass('container');
	    }
	});
</script>


<% # Party page refresh logic: if the host has changed the state of the party, this will refresh the attendees' page %>
<script>
	currentPage = location.pathname
	partyConcluded = <%= @party.concluded %>
	partyResultsReleased = <%= @party.results_released %>
	partyNumberOfEntries = <%= @party.entries.where.not(disguise_id: nil).size %>
	partyPageStateCheckInterval = setInterval(function() {
		if (currentPage !== location.pathname) {
			// If not not on the party page anymore, clear the setInterval
			clearInterval(partyPageStateCheckInterval);
			return;
		}
		// This method will do the check AND perform down-stream actions.
		partyPageStateCheck(<%= @party.id %>);
	},<%= ENV["PARTY_PAGE_REFRESH_RATE"] %>)
</script>