config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  
  resources :party,  only: [:show, :new, :create, :edit, :update, :destroy]
  put 'party/:id/conclude_flip' => 'party#conclude_flip', as: :party_conclude_flip
  put 'party/:id/results_released_flip' => 'party#results_released_flip', as: :results_released_flip
  get 'party/:id/view_results' => 'party#view_results', as: :party_view_results
  get 'party/state_check/:id' => 'party#state_check', as: :party_state_check
  get 'party/:id/get_status' => 'party#get_status', as: :party_get_status

  resources :party_invitation, only: [:create]
  put 'party_invitation/:id/accept' => 'party_invitation#accept', as: :party_invitation_accept

  put 'entry_upsert_clearname/:entry_id' => 'entry#upsert_clearname', as: :entry_user_upsert_clearname

  resources :vote, only: [:update]
  get 'vote/:id/dashboard_ajax' => 'vote#dashboard_ajax', as: :vote_dashboard_ajax

  get 'wine/ajax_search'
  
  put 'shout/create'
  get 'shout/:id/dashboard_ajax' => 'shout#dashboard_ajax', as: :shout_dashboard_ajax
  
  get 'user/:id/edit' => 'user#edit', as: :user_edit
  put 'user/:id' => 'user#update', as: :user_update
  put 'user/update/:user_id' => 'user#update_nickname', as: :update_user_nickname
  delete 'user/:id' => 'user#destroy', as: :user_destroy

  root :to => "static#index"

  get '/signout' => 'sessions#destroy'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	helper :all
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  	def correct_user(path, id)
  		# Controller wide method to help determine correct user
  		if id.to_s!=current_user.id.to_s
  			flash[:error] = "Something went wrong"
  			redirect_to path
  		end
  	end
  	
  	def correct_user_party_host
		if current_user.parties.find_by_id(params[:id]).nil?
			#Party doesn't belong to current_user
			flash[:error] = "Something went wrong"
			redirect_to root_path
		end
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper

	def siteName()
		return "Grape.Social"
	end
	
	def getUsersTimeZone()
		return current_user.timezone rescue "Eastern Time (US & Canada)"
	end
end

app/views/application/_all_codenames.html.erb
<% codenames.each do |codename| %>
	<div class="collection-item">
		<span class="codename-display"><%= codename %></span>
	</div>
<% end %>

app/views/application/_all_entries.html.erb
<table id="entry_disguise_table" class="striped tight-table-td" style="max-width: 600px;">
	<colgroup>
       <col span="1" style="width: 60%;">
       <col span="1" style="width: 40%;">
    </colgroup>
	<thead>
		<tr>
			<th>Wine</th>
			<th>Disguise</th>
		</tr>
	</thead>
	<tbody>
		<% all_entries.each do |entry| %>
			
			<tr>
				<td>
					<div ><%= entry.clearname %></div>
					<div ><%= entry.user.needs_name ? entry.user.email : entry.user.name %></div>
				</td>
				<td class="disguise_tr">
					<span><%= entry.codename %></span>
				</td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/application/_flash_notices.html.erb
<div id="flash_messages">
  <% flash.each do |key, value| %>
    <div class="<%= key %> flash-alert"><%= value %></div>
  <% end %>
</div>

app/views/application/_hostedparties.html.erb
<table class="striped medlarge_display">
	<thead>
	  <tr>
	      <th>Party</th>
	      <th>Date</th>
	      <th>Host</th>
	  </tr>
	</thead>

	<tbody>
	<% hostedparties.each do |hostedparty| %>
	<tr>
		<td><%= link_to hostedparty.name, party_path(hostedparty)%></td>
		<td><%= hostedparty.event_date.strftime("%b %d, %Y") %></td>
		<td><%= hostedparty.user.email.casecmp(current_user.email)==0 ? "me!" : hostedparty.user.email %></td>
	</tr>
	<% end %>

	</tbody>
</table>

<table class="striped small_display">

	<tbody>
	<% hostedparties.each do |hostedparty| %>
	<tr>
		<td>
			<ul>
				<li><%= link_to hostedparty.name, party_path(hostedparty)%> (<%= hostedparty.event_date.strftime("%b %d, %Y") %>)</li>
				<li><b>Host:</b> <%= hostedparty.user.email.casecmp(current_user.email)==0 ? "me!" : hostedparty.user.email %></li>
			</ul>
		</td>
	</tr>
	<% end %>

	</tbody>
</table>

app/views/application/_outstandinginvites.html.erb
<table class="striped tight-table-td medlarge_display">
	<thead>
	  <tr>
	      <th>Party</th>
	      <th>Date</th>
	      <th>Host</th>
	      <th></th>
	  </tr>
	</thead>

	<tbody>

	<% invites.each do |invite| %>
		<tr>
			<td><%= invite.party.name %></td>
			<td><%= invite.party.event_date.strftime("%b %d, %Y") %></td>
			<td><%= invite.party.user.email %></td>
			<td>
				<%= form_tag party_invitation_accept_path(invite), method: 'put' do %>
				  <%= hidden_field_tag :party_id, invite.party.id %>
				  <%= submit_tag 'Accept', :class => "btn" %>
				<% end %>
			</td>
		</tr>
	<% end %>

	</tbody>
</table>

<table class="striped tight-table-td small_display">
	<tbody>
		<% invites.each do |invite| %>
			<tr>
				<td>
					<ul>
						<li><b><%= invite.party.name %></b> (<%= invite.party.event_date.strftime("%b %d, %Y") %>)</li>
						<li><b>From:</b> <%= invite.party.user.email %></li>
						<li>
							<%= form_tag party_invitation_accept_path(invite), method: 'put' do %>
							  <%= hidden_field_tag :party_id, invite.party.id %>
							  <%= submit_tag 'Accept', :class => "btn" %>
							<% end %>
						</li>
					</ul>
				</td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/application/_own_vote.html.erb
<% own_vote_objs.each do |own_vote_obj| %>
    <p class="reveal-name-emphasis" reveal_val="<%= "#{own_vote_obj["name"]} rated #{own_vote_obj["codename"]} a score of #{own_vote_obj["score"]}" %>">?????</p>
<% end %>

app/views/application/_rank_statistics2.html.erb
<div id="<%= reveal_info_pane_id %>" class="reveal-info-pane">
    <p class="reveal-name-emphasis" reveal_val="<%= "#{ordinal} - #{rank_statistics_obj['name']}  : '#{rank_statistics_obj["codename"]}' : #{rank_statistics_obj["clearname"]} : score #{rank_statistics_obj["score"]}" %>">?????</p>
</div>

app/views/application/_vote_list_ajax.html.erb
<table id="voting_table" class="striped tight-table-td">
	<tbody>
		<% votes.each do |vote| %>
			<tr>
				<%= form_for vote, url: vote_path(vote) do |f| %>
				<td id="vote_tr_<%= vote.id %>">
					<div class="vote_tr_div_col1">
						<span class="codename-display"><%= vote.entry.codename %></span>
					</div>
					<div class="vote_tr_div_col2 vote-entry-pane">
						<%= f.select :score, options_for_select( [["(n/a)", nil], ["10 (awesome)", 10], [9, 9], [8, 8], [7, 7], [6, 6], [5, 5], [4, 4], [3, 3], [2, 2], [1, 1], ["0 (crap)", 0]] ,vote.score), {}, :id => "vote_score_" + vote.id.to_s, :class => "browser-default" %>
					</div>
					<br class="small_display" style="clear: left;" />
					<div class="vote_tr_div_col3">
						<%= f.text_area :note, :id => "vote_note_" + vote.id.to_s, :placeholder => "Leave yourself some wine notes...", :class => "browser-default vote_note_textarea"  %>
						<button id="vote_save_btn_<%= vote.id %>" onclick="submitVoteChange(<%= vote.id %>)" type="button" class="btn btn-default disabled">Save</button>
						<button id="vote_cancel_btn_<%= vote.id %>" onclick="revertVoteChange(<%= vote.id %>)" type="button" class="btn btn-default disabled">Cancel</button>
					</div>
					<br class="medlarge_display" style="clear: left;" />
				</td>
				<% end %>
			</tr>
			<tr class="spacer"></tr>
			<script>
				//Ajax related, recrod the original value
				originalVoteScoreByID['<%= vote.id %>']="<%= vote.score %>";
				originalVoteNoteByID['<%= vote.id %>']="<%= vote.note %>";
				timeoutMap['vote_note_<%= vote.id %>'] = [];
				
				$("#vote_score_<%= vote.id %>").change(function () {onVoteChange(<%= vote.id %>)});
				$("#vote_note_<%= vote.id %>").keyup(function () {onVoteChange(<%= vote.id %>)});
			</script>
		<% end %>
	</tbody>
</table>