config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  
  resources :party,  only: [:show, :new, :create, :edit, :update, :destroy]
  put 'party/:id/conclude_flip' => 'party#conclude_flip', as: :party_conclude_flip
  put 'party/:id/results_released_flip' => 'party#results_released_flip', as: :results_released_flip
  get 'party/:id/view_results' => 'party#view_results', as: :party_view_results
  get 'party/state_check/:id' => 'party#state_check', as: :party_state_check
  get 'party/:id/get_status' => 'party#get_status', as: :party_get_status

  resources :party_invitation, only: [:create]
  put 'party_invitation/:id/accept' => 'party_invitation#accept', as: :party_invitation_accept

  put 'entry_upsert_clearname/:entry_id' => 'entry#upsert_clearname', as: :entry_user_upsert_clearname

  resources :vote, only: [:update]
  get 'vote/:id/dashboard_ajax' => 'vote#dashboard_ajax', as: :vote_dashboard_ajax

  get 'wine/ajax_search'
  
  put 'shout/create'
  get 'shout/:id/dashboard_ajax' => 'shout#dashboard_ajax', as: :shout_dashboard_ajax
  
  get 'user/:id/edit' => 'user#edit', as: :user_edit
  put 'user/:id' => 'user#update', as: :user_update
  put 'user/update/:user_id' => 'user#update_nickname', as: :update_user_nickname
  delete 'user/:id' => 'user#destroy', as: :user_destroy

  root :to => "static#index"

  get '/signout' => 'sessions#destroy'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta property="og:site_name" content="<%= siteName %>"/>
	<meta property="og:url" content="http://www.grape.social/" />
	<meta property="og:title" content="Host a wine tasting party." />
	<meta property="og:description" content="Host a tasting party where your guests can rate each wine. We'll help you find the wine you enjoy the most.  1) Start a party and invite your friends.  2) Disguise the wine.  3) Rate the wine.  4) Enjoy your wine.  We'll do the math and analytics in the Cloud so you can enjoy your wine socially." />
	<meta property="fb:app_id" content="<%= ENV['FB_APPID'] %>" />
	<meta property="og:image" content="<%= image_url("red-wine-glasses_f14u81PO_small.png", id: "static_page_graphic") %>" />
	
  <title><%= siteName() %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!--Let browser know website is optimized for mobile-->
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1"/>
</head>
<body>
 <nav class="purple darken-3" role="navigation">
    <div class="nav-wrapper container">
    	<%= link_to siteName(), root_path, class: "brand-logo", id: "logo-container" %>

    	<ul id="nav-mobile" class="side-nav">
			<% if signed_in? %>
				<li><%= link_to siteName(), root_path %></li>
				<li><%= link_to current_user.needs_name ? current_user.email : current_user.name, user_edit_path(current_user) %></li>
				<li><%= link_to "New Party", new_party_path %></li>
				<li><%= link_to "Sign Out", signout_path %></li>
			<% else %>
				<li><%= link_to "Sign-Up", "/users/sign_up" %></li>
				<li><%= link_to "Login", "/users/sign_in" %></li>
			<% end %>
		</ul>

		<ul class="right hide-on-med-and-down">
			<% if signed_in? %>
				<li><%= link_to current_user.needs_name ? current_user.email : current_user.name, user_edit_path(current_user) %></li>
				<li><%= link_to "New Party", new_party_path %></li>
				<li><%= link_to "Sign Out", signout_path %></li>
			<% else %>
				<li><%= link_to "Sign-Up", "/users/sign_up" %></li>
				<li><%= link_to "Login", "/users/sign_in" %></li>
			<% end %>
		</ul>

      <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="mdi-navigation-menu"></i></a>
    </div>
  </nav>

<div class="row">
	<div class="col l6 offset-l3 m12 s12 grid-example">
		<div id="flash_messages_div">
			<%= render "application/flash_notices" %>
		</div>
	</div>
</div>

<%= yield %>

<div class="roww">
	<div id="overall_footer" class="center-align">
		<% if signed_in? %>
			<span><%= link_to siteName(), root_path %>  |  <%= link_to current_user.needs_name ? current_user.email : current_user.name, user_edit_path(current_user) %></span>
		<% else %>
			<span><%= link_to siteName(), root_path %></span>
		<% end %>
	</div>
</div>

<!-- Modal for user.name -->
<% if signed_in? %>
	<div id="username_modal" class="modal">
		<div class="modal-content">
			<h5>You need a 'name' so the host can identify winners</h5>
			<h6>(instead of by email address)</h6>
			<input type="text" id="current_user_name_text_area" class="browser-default" placeholder="(cool handle ex. RocketDan, KimofTheNorth)">
			<button id="current_user_name_btn" onclick="submitNameChange(<%= current_user.id %>)" type="button" class="btn btn-default">Save</button>
			<script>
				$("#current_user_name_text_area").on('keyup', function (e) {
				    if (e.keyCode == 13) {
				        submitNameChange(<%= current_user.id %>);
				    }
				});
			</script>
		</div>
	</div>
<% end %>

<script>
	// Activate the modal-triggers for all modals.
	$(document).ready(function(){
		// the "href" attribute of .modal-trigger must specify the modal ID that wants to be triggered
		$('.modal-trigger').leanModal();
		// Every page, check if the User has a name.  Necessary for UX for interactivity.
		<% if signed_in? && current_user.needs_name %>
			$('#username_modal').openModal();
		<% end %>
	});
</script>


</body>
</html>